name: OPB Server Deploy

on:
  push:
    branches:
      - production

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 21

      - name: Build project
        run: mvn clean install
        working-directory: opb-server

      - name: Docker HUB Login
        run: echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

      - name: Build docker image
        run: docker build -t ${{secrets.DOCKER_USER}}/opb-server .
        working-directory: opb-server

      - name: Push image docker
        run: docker push ${{secrets.DOCKER_USER}}/opb-server

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from Docker HUB
        run: docker pull ${{secrets.DOCKER_USER}}/opb-server:latest

      - name: Run docker container
        run: docker run -d -p 8080:8080 --name deploy-opb-server ${{secrets.DOCKER_USER}}/opb-server:latest