name: OPB Server Deploy

on:
  push:
    branches:
      - production

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 21

      - name: Build project
        run: mvn clean install
        working-directory: opb-server

      - name: Docker HUB Login
        run: echo "${{secrets.DOCKER_PASS}}" | docker login -u "${{secrets.DOCKER_USER}}" --password-stdin

      - name: Build docker image
        run: docker build -t ${{secrets.DOCKER_USER}}/opb-server .
        working-directory: opb-server

      - name: Push image docker
        run: docker push ${{secrets.DOCKER_USER}}/opb-server

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Remove old postgres container (if exists)
        run: docker rm -f deploy-postgres || true

      - name: Upload PostgreSQL container
        run: |
          docker run -d \
          --name deploy-postgres \
          -e POSTGRES_USER=${{secrets.POSTGRES_USER}} \
          -e POSTGRES_PASSWORD=${{secrets.POSTGRES_PASSWORD}} \
          -e POSTGRES_DB=${{secrets.POSTGRES_DB}} \
          -p 5432:5432 \
          postgres:17.4

      - name: Waiting database is up to date
        run: |
          until docker exec deploy-postgres pg_isready -U ${{secrets.POSTGRES_USER}}; do sleep 1; done

      - name: Run tests
        run: |
          docker exec deploy-postgres psql -U ${{secrets.POSTGRES_USER}} -d ${{secrets.POSTGRES_DB}} -c '\l'
        env:
          PGPASSWORD: ${{secrets.POSTGRES_PASSWORD}}

      - name: Pull image from Docker HUB
        run: docker pull ${{secrets.DOCKER_USER}}/opb-server:latest

      - name: Remove old opb-server container (if exists)
        run: docker rm -f deploy-opb-server || true

      - name: Run docker container
        run: docker run -d -p 8080:8080 --name deploy-opb-server ${{secrets.DOCKER_USER}}/opb-server:latest